### ISSUE TITLE
Think about intermediate theme between light and dark

### ISSUE THREAD

**Issue by i582** [vlang-association/docs#4]
See Discord discussion: https://discord.com/channels/592103645835821068/631271043876519967/1099192473206661140

**Comment by devsou-com** [comment]
@i582 I myself started this discussion on discord. I think there is no need to implement such a feature, I'm satisfied with the dark theme. It was more of a comment on what I think about choosing ONLY between light and dark themes.

I keep thinking that a dark bluish tone matches the V logo, but how I consider myself a terrible CSS designer, I prefer not to try to do anything. But if I ever feel comfortable trying to do something about it, I'll be very happy to make a pull request.

For now, it's better to close this issue, and focus on more important things for the project.

**Comment by i582** [comment]
Hi, @devsou-com 

Thanks for the comment, maybe someone else will think it's a good idea to have a theme like this, so I suggest keeping the issue open so people can come and leave thoughts/vote for it.
I'll keep this issue in mind, but don't do it yet.
What do you think?

**Comment by devsou-com** [comment]
@i582 you make me feel bad by not closing this issue, as I feel obligated to do something about it. Damn you! (just kidding).

**Comment by i582** [comment]
@devsou-com closed :)
